#DNA - Counting DNA Nucleotides by Teodora Kovacevic

string = "ACAACGCTCGGGCGCCCTTAATCACGCTGGTACCCTCAAAGCTTGCGGTTTGCATATACGGCATCTCTGTAACAAATCAATTCCAGCTCTTGCAACTGTACCTTAGTCCCCCTCGACTCACTAAAACTCGAAACCTTCTTTGCCCTATACCATAGAGCACCACGCCATCCGAGCCGTCCTTACGACCCGAGTGCCTATGCAGACATTCAGCGTGACACCAATGAGCACTGCGAACGACGGAATCCTTCGTCTGTTGGCCTTCCTGTCATAGTACTAAGATAATCCAACATCTCGCCGGAGGGATTTCTCCAGGAAGTAGGGATTTACTAACATACCGCACGTATAACTGGGGTAATCGAGTCATCTGGAGAGATAGATGACCTCACGGGCACCTAGTATGTTATCGGATTTGCAACCTCTTCTAGGCGCTTGGTGCACGTTTGAACGCATGGCCCCAGGCTATATATTAGAGGCCGTAGACAACACCAGCGGGACACGCCGCACCCGGCGCCGGAGTGCTTCCATACACTTTGCGGGTTCATAATAACCTGTATAGCGAATCCGGATGAGTATTGTGCGGGCGACAGGTAGGATGAGCCTGTTGATAAATGTTAGTCATGCCTTCAGCCGCGTAGACTCAAACGTAGAAGAGGAGTCCGGCTGTACGCACCACGCTCGTCCTGATTCATGCAAAATCCGATCAGGCAAGGTAAACGAGTCAGTGGGATCGCGTGATCTGTTGCTCTTATGGTCGCTTCTCCCCTCGGACGTATCCTTGCTTGCCCCAGGTGATGTGAAGCCTCGTCTAGGAGAAAACT"
a=0
t=0
g=0
c=0

for i in string:
    if i == "A":
        a+=1
    elif i=="T":
        t+=1
    elif i=="G":
        g+=1
    else:
        c+=1
print(a,c,g,t)


