#REVC - Complementing a Strand of DNA by Teodora Kovacevic

original ="CTGAGTACCCTCTGTTTAGCGACGGAGTCGGCAGCACCGTCACTTCTCATACCATCGTACGTTGTAAATGATGATTGGGGTAAAGTACCCATCAGACAGGCGATTCCCATCGGGTCGCCCAGTTGAGTCGCAAACCGGGCGGGTGTTAAGGGGCCTGCGGGAACATCTAGCGCGGATATGGGAACTGCCACGAAGCTTCCCCATCGTGTCCGATAATAGACCGGCATTTAGATCCTGGAAAAGGAAACCCCTCCGCTGCTTCCCTCAGCCGGACGAGGCGCGGGCAGGGATGCACGAGGAAGAACTGAAAATGTGACCCGTCCGTTCCCACCGCCCCTCTTCGGTGCCGCCGGGTTAGGTACCAGAACAGCAGGTTCTCCAACAGTGTCCCACAAGTTCGATGATTCTGAGGTGTCCAGTCGCTCAGAGTTCCTAACATCGGAATAACTAAAACCGCCTACAAGCTCCCCATTGACAAAAGGCTGCTATCGCGGATGAAAGTATACTGTGGAAAGCGATGGACTTCGTATTTGAAGTGGATAACTTAGGATGTTTAGCCCGAGCTCGAAACCTGTGAAGCTCCTGGTTCTCTTATTGACTGAGGCCTCGAACGCTCCTATGTTTAACGAGTGCGTCGGGTCATTCGGAAAATACGTCCAAGACCGAGGGTTAGCTTAGGCCTAGATGGTGTCTTTTTGTGAGGAAGTGTTCCAGCGGTTTTATCGTCTTAGGGATATGGCGACTCCTAATAGCCTCGTAGGGAGCATTAGTGTCTAAGAAATCTAAACCTATATCACCTAGGAACCAGGAACCCCCGCATGATCCCCCAACACGGTGATCGTATAAGAGTGACCACGG"
reverse = original [::-1]
complement = ""
for i in reverse:
    if i == "A":
        complement+="T"
    if i == "T":
        complement+="A"
    if i == "G":
        complement+="C"
    if i == "C":
        complement+="G"
print (complement)

    
    
    